version: '3'

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - socketproxy

  traefik:
    image: traefik:v2.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - socketproxy
    ports:
      - 80:80
      - 443:443
      - 9989:9989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic/:/etc/traefik/conf/:ro
      - ./certs/:/etc/traefik/certs:ro
networks:
  socketproxy:
    external: true
  proxy:
    external: true
